name: Production

on:
  pull_request:
    types: ['opened', 'edited', 'synchronize', 'closed']
    branches: ['main']

jobs:
  build_and_copy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Copy build artifacts to a folder
        run: mkdir build-output && cp -r dist build-output/
      - name: Archive build artifacts
        run: tar -czf build.tar.gz build-output
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build.tar.gz

  copy_to_runner:
    needs: build_and_copy
    runs-on: self-hosted
    environment: production

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: .
      - name: Extract build artifacts
        run: tar -xzf build.tar.gz
      - name: Copy folder to where nginx expects it to be
        run: cp -r build-output ${{secrets.COPY_TO_FOLDER}}
